/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/paloma/catkin_ws/mavros_ws/src/sp_pos/msg/utmData.msg
 *
 */


#ifndef SP_POS_MESSAGE_UTMDATA_H
#define SP_POS_MESSAGE_UTMDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sp_pos
{
template <class ContainerAllocator>
struct utmData_
{
  typedef utmData_<ContainerAllocator> Type;

  utmData_()
    : utmNorthing(0.0)
    , utmEasting(0.0)
    , utmZone()  {
    }
  utmData_(const ContainerAllocator& _alloc)
    : utmNorthing(0.0)
    , utmEasting(0.0)
    , utmZone(_alloc)  {
    }



   typedef double _utmNorthing_type;
  _utmNorthing_type utmNorthing;

   typedef double _utmEasting_type;
  _utmEasting_type utmEasting;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _utmZone_type;
  _utmZone_type utmZone;




  typedef boost::shared_ptr< ::sp_pos::utmData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sp_pos::utmData_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct utmData_

typedef ::sp_pos::utmData_<std::allocator<void> > utmData;

typedef boost::shared_ptr< ::sp_pos::utmData > utmDataPtr;
typedef boost::shared_ptr< ::sp_pos::utmData const> utmDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sp_pos::utmData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sp_pos::utmData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sp_pos

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sp_pos': ['/home/paloma/catkin_ws/mavros_ws/src/sp_pos/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sp_pos::utmData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sp_pos::utmData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sp_pos::utmData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sp_pos::utmData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sp_pos::utmData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sp_pos::utmData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sp_pos::utmData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49b19eb1db7e204c2b9962b01694fa27";
  }

  static const char* value(const ::sp_pos::utmData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49b19eb1db7e204cULL;
  static const uint64_t static_value2 = 0x2b9962b01694fa27ULL;
};

template<class ContainerAllocator>
struct DataType< ::sp_pos::utmData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sp_pos/utmData";
  }

  static const char* value(const ::sp_pos::utmData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sp_pos::utmData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 utmNorthing\n\
float64 utmEasting\n\
string utmZone\n\
";
  }

  static const char* value(const ::sp_pos::utmData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sp_pos::utmData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.utmNorthing);
      stream.next(m.utmEasting);
      stream.next(m.utmZone);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct utmData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sp_pos::utmData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sp_pos::utmData_<ContainerAllocator>& v)
  {
    s << indent << "utmNorthing: ";
    Printer<double>::stream(s, indent + "  ", v.utmNorthing);
    s << indent << "utmEasting: ";
    Printer<double>::stream(s, indent + "  ", v.utmEasting);
    s << indent << "utmZone: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.utmZone);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SP_POS_MESSAGE_UTMDATA_H
